### ISSUE TITLE
Allow setting different landing page on zimit recipes

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#1017]
Not entirely sure this is a zimit or zimfarm issue.

MWoffliner recipes have a `Main Page` field that allows recipe creator to set a different landing page than the default one. Some zimit-generated zim files actually focus on content that is not exactly presented on the landing page ([Survivor Library](https://library.kiwix.org/viewer#survivorlibrary.com_en_all) is one that comes to mind where the [Download books](https://library.kiwix.org/viewer#survivorlibrary.com_en_all/www.survivorlibrary.com/index.php/main-library-index/) tab is the more interesting part).

Generally speaking I could see this being needed with resource repositories where the default main page is used for dynamic (news and announcements) content, which in an offline setting isn't as important.

**Comment by rgaudin** [comment]
I don't understand what you want. zimit takes a homepage as main argument. So you already specify your homepage. There are additional (and more difficult to use!) arguments to tweak what to crawl (defaults to homepage _folder_ as a prefix).

**Comment by benoit74** [comment]
Customizing home page is already here by default.

In survivor library, the home page was the "download books" page, but I changed it to the website home page when we decided to grab the whole website instead of just books (https://github.com/openzim/zim-requests/issues/1130#issuecomment-2344153607). 

Except when we do not grab the whole website, in general I don't agree about customizing home pages, website owners have their reasons and I find it a bit weird to overrule them (and I feel like it breaks the navigation flow imagined by website owner).

Anyway, this is another discussion and zimit already has everything needed.
