### ISSUE TITLE
Workers should be able to run all tasks (they can physically handle)

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#202]
Today, a worker looks at a queue. If that queue is empty then nothing will be done with that worker. Currently we have workers which are sleeping while others struggle to empty their queue. This is not optimal. This worker should instead looks at the smaller queues (not the bigger ones) to help to empty that queues as quickly as possible.

**Comment by rgaudin** [comment]
This is not exactly how it works at the moment.

* We have three standard queues: `small`, `medium`, `large`.
* What goes into those is not defined at the moment. I scheduled small wikis to `small`, most selections and tops `medium` and complete wikis to `large` for instance.
* Workers register to one or more queue via the `QUEUES` env variable.

*current queues and consumers*:

* `small`: wmf1, wmf2, wmf3, wmf4, wmf5, kelson, reg
* `medium`: wmf1, wmf2, wmf3, wmf4
* `large`: -

So when a task is fired (more on that bellow), rabbit round-robin assigns it to a free worker registered to the specified queue.
At the moment, **no `large` request would be handled** because there is no worker registered.

It is worth noting that when starting a worker, you can define a `CONCURRENCY` variable. If not set, celery will use the number of CPUs so we have more *workers* available than the number registered.
I couldn't get the information about those though.

I could confirm that both the assignment of task and concurrency works as expected.

So, if workers are idle while others are busy and there are pending creations, it is likely because the pending ones are in a different queue.

Now I think the problem we are currently facing revolves around the *tasking* of schedules:

* `Schedule` objects are representation of what we want.
* `Task` represent a job request, to be executed now, by an available worker.

At the moment, @automactic is requesting the creation of the `Tasks` from the `Schedules` somewhat-manually.
If you look at the zimfarm tasks right now, you'll find that most workers are idle (or busy with a `small` selection I fired to validate the above mentioned behavior).

Also, we need to have a `large`-capable worker, of course.

**Comment by automactic** [comment]
Previously we have mwofflienr4 be the dedicated large task runner. However, due to mwoffliner memory problem, none of the large tasks are succeeding. Per request from @kelson42 on slack, we stopped running large tasks.

To the original question of the issue, I think it can be solved by using a combo of priorities and queue. To be specific, more capable nodes will subscribe to all three queue, but more important tasks (usually larger tasks in our case) will have higher priorities.

**Comment by kelson42** [comment]
@automactic That is great. Thank you for (re-)explaning me this. I think what still needs to be done here: Take the queues in order: first one first, and then if empty, second, etc.. Otherwise this might be a source of inefficiency.

**Comment by rgaudin** [comment]
OK, my understanding is that @kelson42 proposes a flexible solution in which the worker host chooses (by ordering the `QUEUES` env values) which queue should be cleared before tasks from another is ran.

This is not directly doable with celery/rabbit as we are using a rabbit as a message broker meaning he's the one responsible for assigning tasks to workers and not the other way around (workers querying tasks).

We _could_ implement it by starting/stopping celery-workers on the fly every time a task is completed (ie. if there's no large task, start a `medium`-only celery-worker) but as you probably figured, it would be a mess.

That said, I think we can achieve the end-result using a different strategy, as @automactic suggested.

**objective**: worker are used as much as possible. no task-capable worker idleing when there's work to do.

Using celery priorities, we can have:
* workers subscribe to all queues they can handle (`large,medium,small` for `mwoffliner4` for instance).
* queues are configured to handle priorities
* task are sent with priorities based on the queues we'll route them to:
  * `small`: `1` (our default)
  * `medium`: `2`
  * `large`: `3`
  * `debug`: `5`

So basically, larger tasks have higher priorities.

In action, this result in large tasks being pick before medium or small tasks by large-capable workers. And so on.

* Would a task be interrupted by an higher priority one? **no**.
* can we still end-up with idle workers? **yes**, if we have a single worker/process handling large task for example and you only have large tasks in the pipe. Otherwise, tasks are split across free-and-capable workers (rabbit's round-robin, we don't manage this).
* What happens if we have just one `small` and one `large` worker with 10 small tasks and 2 large ones? **what we want**: the large worker will work on the large tasks and once those are complete take some small ones (if not already completed by the other worker).

---

so @kelson42, this is conceptually different from what you requested but the objective is achieved in a cleaner/simpler manner.

**Comment by kelson42** [comment]
@rgaudin Looks good to me, you indeed achieve the same result.

**Comment by rgaudin** [comment]
Thanks for the feedback. Unfortunately, after many tests it appears that priorities in rabbit/celery doesn't work exactly as expected: priorities apply only within a queue.

So what works is setting a higher priority for task `wikipedia_bm` than for `wikipedia_wo` inside the `small` queue for instance, but we're not interested in this behavior.

---
We _could_ use a single queue for all tasks which would solve the priority issue but would create worst other issues:
* we'd have to filter tasks upon reception as all workers can't execute all tasks
* to filter we'd have to reject/requeue tasks
* it would create a lot of work and use many attempts to finally reach a capable worker
* we might end-up with an endless loop if a capable worker is not available.

We _could_ use direct worker queues: send tasks to specific workers but it would mean assigning tasks to workers based on load and making sure it's efficient: lots of code to replicate celery… and we'd be using rabbit just as a transport. 

---
I don't have any direct way forward in fixing this so while we think about it, here's a recap of where we're at with the current solution.

### our goal (recap)

* don't have idle workers if possible
* stupid to have a large worker idle if there are non-large (smaller) tasks to be done.
* stupid to have a large worker busy with small tasks if there are large ones to be done.

### Data
Bellow is an overview of how load is balanced across queues and workers. It's an example but similar requests provides similar results so it's somewhat reliable.

<table>
<tr><th>worker \ tasks</th><th>small</th><th>medium</th><th>large</th><th>% sm</th><th>% md</th><th>% lg</th></tr>
<tr><th>small1</th><td>10</td><td>0</td><td>0</td><td>34%</td><td>0%</td><td>0%</td></tr>
<tr><th>small2</th><td>9</td><td>0</td><td>0</td><td>31%</td><td>0%</td><td>0%</td></tr>
<tr><th>medium1</th><td>6</td><td>12</td><td>0</td><td>21%</td><td>86%</td><td>0%</td></tr>
<tr><th>large1</th><td>4</td><td>2</td><td>7</td><td>14%</td><td>14%</td><td>100%</td></tr>
<tr><th>total</th><td>29</td><td>14</td><td>7</td><td colspan="3">50</td></tr>
</table>

Here's the orders in which tasks are executed inside each worker:

**small1**
1. small
1. small
1. small
1. small
1. small
1. small
1. small
1. small
1. small
1. small

**small2**
1. small
1. small
1. small
1. small
1. small
1. small
1. small
1. small
1. small

**medium1**
1. small
1. small
1. small
1. small
1. small
1. medium
1. medium
1. small
1. medium
1. medium
1. medium
1. medium
1. medium
1. medium
1. medium
1. medium
1. medium
1. medium

**large**
1. small
1. small
1. small
1. small
1. large
1. large
1. large
1. large
1. large
1. medium
1. large
1. medium
1. large

### Config

* current schedules repartition (in zimfarm): `56%` small, `28%` medium and `16%` large. That's why this 50 schedules example is using same shares for each size.
* `CONCURRENCY=1` on all workers for this so it's clearer.
* all workers request just `1` additional task per worker (`worker_prefetch_multiplier=1` and `task_acks_late=True`)
* all tasks scheduled approximately together.

### Results

* on start, worker receives at least 2 tasks if there are enough in rabbit (with `prefecth_multiplier=1`).
* once a task is completed (`ack_late=True`), another one is received.
* worker/tasks attribution is based on round-robin: from rabbit to workers (within queue)
* when celery/worker has multiple tasks, it executes alternatively from the different queues. In our example it rarely happens as we receive tasks one by one from rabbit and execute.
* we want to have the least possible tasks in worker/celery to not prevent those from being executed by other workers.

### Conclusions

* current behavior is not satisfactory: our `medium1` and `large1` workers both execute 4/5 `small` tasks before starting on `medium` and `large` ones while we have such tasks in rabbit. This is due to the order in which tasks are sent to rabbit as tasks are received and sent to workers in real time. So before rabbit receives the first medium tasks, it has already sent small ones to workers.
* it's not that bad though as we don't have workers idle while they could be working. It's just that we can't completely leave small tasks to small workers when we have medium and large scheduled.
* I may have missed something but I think we won't be able to achieve exactly what we want with celery/rabbit.

**Comment by rgaudin** [comment]
discussing this with @kelson42, we might be able to overcome this by using a single prioritized queue with size-aware tasks like `LargeMwoffliner()` to which workers would register based on their capabilities.

Just food for thought at the moment.

**Comment by kelson42** [comment]
@rgaudin Sorry to come with another wild idea, back to the first scenario we had in mind. Why not, each time a task has been completed, connect first to the "large" queue, and then when nothing to do, to the "medium" queue, etc...?

**Comment by rgaudin** [comment]
I suppose you're going back to this because it's what we'd like but what you're proposing is a diversion around celery.

rabbit's goal is to build and manage queues. most of its logic goes towards building those queues.
Once a message (a task in our job-oriented use case) is in the queue, there's not much to be done (queue could be reorganized based on priority).

On the other end, clients (workers) subscribe to queues through various mechanism (exchanges, binding_keys/topics, queue names).

we **won't be able to do exactly what we want with rabbit** as what we need (based on description above) is the ability to filter messages at run time using both backend-side information (scheduled tasks stack) and client-side info (state of worker, capability) : *if not busy and there's not large task, take the small one* for instance.

this is very different than what rabbit is built for. rabbit is a message broker. it buffers and pushes messages.


Given that, as per @kelson42's suggestion on Sunday's call, an option could be:

### 1. Backend endpoint to request a task (`GET /api/tasks/scheduled`)

Caller (worker) would provide `capability` (`large`,`medium`,`small`).
Based on this info and the type of tasks scheduled in the DB (waiting in the `tasks` collection), the backend will reply with just one or zero task to be executed.

### 2. Backend endpoint to update a task (`PATCH /api/tasks/xxxxx`)

If leveraging the API from the previous point, it makes sense to collect updates to tasks (statuses and results mostly) through a unique API.

Requests over HTTP means straightforward error management.

### 3. Lightweight messaging

Not mandatory but we could use a two-way messaging system so that the backend would push messages on new scheduled-tasks. This would remove the need for polling from the worker (along with an on-start request).

It could be based on rabbit via [Pika](https://pika.readthedocs.io) or a simple [py-zmq](https://learning-0mq-with-pyzmq.readthedocs.io/) or something else.

---

**Pros**:

* simple, flexible, readable, centralized task assignment logic on the backend.
* more flexibility: we can later add a `type` to tasks that we want (like for dedicated youtube/stackexchange workers) or `priority` with limited impact on workers.
* allows us to work stateless (workers making state less requests)

**Cons**:

* without celery, we'd have to handle:
  * concurrency. _could be ignored with hosts starting multiple single-process workers (or a wrapper doing it automatically)_
  * manually starting processes for tasks.
  * manually killing processes on cancel. _not much of a problem as our tasks are docker based and `docker.stop()` would take care of it_.
* have to implement it.

---

So just to make it clearer, here's a (fake) output we could have on such a worker

```
starting workerX, looping forever
startup-call to API...
  no task to run
received new-schedule message from backend
calling API...
  no task to run
received new-schedule message from backend
   received task #abcdefghij
running task #abcdefghij
  container started
  calling API to update task
received new-schedule message from backend (ignoring: busy)
  container succeeded
  calling API to update task
  task completed
   calling API to update task
post-task call to API...
  no task to run
One hour without message, calling API...
  no task to run
```

**Comment by rgaudin** [comment]
On Slack, @automactic  suggested we take a look at [Jenkins](https://jenkins.io).

It looks like it's a Java-written ([docker image avail](https://hub.docker.com/r/jenkins/jenkins/)) server/agents tool to produce builds.

On the agent/worker side, we'd define a recipe and the agent would execute it.

**Note**: I haven't looked at the doc in detail yet. **Will update/respond once I have**.

**Pros**:

* Exists
* Widely used, actively supported, scales.
* Supports docker out-of-the-box. A recipe can pull a docker image and run a command on it.
* @automatic using it at work.

**Cons**:

* Server [looks resources consuming](https://jenkins.io/doc/pipeline/tour/getting-started/).
* Not much we can reuse from current worker code base.
* have to investigate how/if we can do exactly what we wanted (both on client and server side).

**Comment by kelson42** [comment]
I have been using Jenkins quite intensively for the last 4 years. I wonder how do you plan to:
* Put tasks with all the parameters in Jenkins
* Get the workers pulling them
* Dealing with the priority challenge
