### ISSUE TITLE
Set ulimits properly by starting scraper docker containers

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#239]
Many scraper containers need a lot of I/O resources, it is important that the OS does not limit artificially the access to the HW resource. In addition we have already errors which let us think that we already reach this kind of limits. See for example: https://github.com/openzim/mwoffliner/issues/765

Would be could to start Docker containers with the adequat comment to achieve something like this:
```
nofile unlimited
stack  unlimited
```

Related docker documentation:
https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit

**Comment by rgaudin** [comment]
OK, I've spent some good time trying to figure this out and my suggestion is that **we leave it as it is** 😉

### Explanation

First, @kelson42's favorite comment “_What problem are you trying to fix?_” applies here because the [referenced issue](/openzim/mwoffliner/issues/765) clearly mentions a TCP socket so something outside the scope of this issue.
Worker is not connecting to redis using TCP anymore (some workers pending restart though).

Now, it is clear that scrappers are ultra-intensive I/O consumers and we don't want the OS to artificially limit those.

[zimwriterfs' Dockerfile](https://github.com/openzim/zimwriterfs/blob/master/docker/Dockerfile#L4) (reputed to work with large ZIM) does set `unlimited` to `nofile` and `stack` in its `/etc/security/limits.conf`. It had **no effect** as [`*` doesn't apply to root](https://bugs.launchpad.net/ubuntu/+source/pam/+bug/65244). `root` needs to be specified separatly.
You can easily confirm this by running `docker run -it openzim/zimwriterfs /bin/bash -c 'ulimit -s'`

Docker containers can be assigned limits using the [`--limit` option](https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit) but, if not set, inherits those of the docker daemon (running as root).
Those limits can be checked  via `cat /proc/$(ps -ef | grep dockerd | head -n 1 |awk '{ print $2 }')/limits`

It means that **doing nothing gets us as much I/O as the root of the host** which is probably what we want.

`--ulimit` option is meant to restrict access to resources, not to increase them ; of course, you can't set ulimit of a container to a higher value than what the docker daemon is allowed to access.

Lastly, setting `--ulimit` is **very fragile**:

* it doesn't support `unlimited` values. It expects an `int` and even `-1` is not accepted. having to deal with actual numbers would be a nightmare I guess.
* there are conversion issues. Although the documentation says it does zero conversion, setting a `8192` value for `stack` ends up  as `8` while it displays `8192` when not set.
* It fails easily. If for some reason the value is considered invalid (too high, above host limits, etc), container will refuse to start. It can be silent or an unclear (generic) error message.
* It's not reliable. Running a container with `--ulimit` using the very same command several times **sometimes** doesn't work.

**Comment by kelson42** [comment]
@rgaudin Thank you for the analysis. As a first consequence if have removed uless `ulimit` commands in `Dockerfile` of:
* mwoffliner: https://github.com/openzim/mwoffliner/commit/e033686562e9d92ca0296eca68cdaf08df4abb70
* zimwriterfs: https://github.com/openzim/zimwriterfs/commit/deaac3d9636dff680596869623d340bd3516c9b3

@rgaudin I think the best we can do here, is to update zimfarm README? Could you do that?
