### ISSUE TITLE
Improper wikivoyage landing pages

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#257]
Looking at http://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_novid_2019-06.zim (and nopic), the landing page is some weird page labeled as "Wikivoyage offline Reader expedition", but there is no such page on wiki (the wiki redirects to [Offline expedition](https://en.wikivoyage.org/wiki/Wikivoyage:Offline_reader_Expedition) and it is very different. I then looked into the zimfarm and every single instance of WikiVoyage in every other language is scheduled with a similar (non existant) landing page. What happened there?

**Comment by kelson42** [comment]
This is a content related stuff, should be in the "zim-requests" repo.

**Comment by Popolechien** [comment]
Well if it is related to scraping it should rather be in the mwoffliner repo, shouldn't it? 

In "zim-requests" I read _requests for zims_

**Comment by kelson42** [comment]
@Popolechien The page exists, see https://en.wikivoyage.org/w/index.php?title=Wikivoyage:Offline_reader_Expedition/Home_page&action=history. This is the page we use since 4 years. So here it works like configured.

@Popolechien Regarding other wikivoyages. It is not true that they have the same custom main page. Almost all of them don't have one... but we have a refreshing problem if values are empty, see #258

**Comment by kelson42** [comment]
@Popolechien Code problems go to "mwoffliner" repo, configuration problems go to "zim-requests" repo.
