### ISSUE TITLE
Workers fails to report a task as finished

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#268]
We have seen that for this task:
https://farm.openzim.org/tasks/5d24550f6976bb2bc5e19ab7

All the work has been done properly and the file has even been uploaded properly.

But the task is still ongoing in the farm. The backend is not aware that the task has been finished properly by the worker.

```
[2019-07-09 18:36:02,135: INFO/ForkPoolWorker-1] Uploading files, mwoffliner_5d24550f6976bb2bc5e19ab7.log.xz - 693392
[2019-07-09 18:36:05,572: INFO/ForkPoolWorker-1] offliner.mwoffliner[5d24550f6976bb2bc5e19ab7]: MWOffliner finished, mwUrl: https://en.wikipedia.org/, exit code: 0
[2019-07-09 18:36:07,095: INFO/ForkPoolWorker-1] Uploading files, redis_5d24550f6976bb2bc5e19ab7.log.xz - 876
[2019-07-09 18:36:08,829: INFO/ForkPoolWorker-1] Uploading files, wikipedia_en_movies_2019-07.zim - 58526944285
[2019-07-09 21:12:24,972: INFO/ForkPoolWorker-1] Task offliner.mwoffliner[5d24550f6976bb2bc5e19ab7] succeeded in 44582.97533836588s: [{'name': 'wikipedia_en_movies_2019-07.zim', 'size': 58526944285}]
```

It seems that for some reason, the backend has not been reached properly by the worker:
```
[2019-07-10 07:16:37,323: INFO/MainProcess] missed heartbeat from automactic@mwoffliner1.mwoffliner.eqiad.wmflabs
[2019-07-10 07:16:37,324: INFO/MainProcess] missed heartbeat from automactic@mwoffliner3.mwoffliner.eqiad.wmflabs
[2019-07-10 07:16:37,324: INFO/MainProcess] missed heartbeat from automactic@mwoffliner2.mwoffliner.eqiad.wmflabs
[2019-07-10 07:17:21,941: WARNING/MainProcess] Substantial drift from automactic@mwoffliner1.mwoffliner.eqiad.wmflabs may mean clocks are out of sync.  Current drift is
49 seconds.  [orig: 2019-07-10 07:17:21.941672 recv: 2019-07-10 07:16:32.831178]

[2019-07-10 07:17:21,942: WARNING/MainProcess] Substantial drift from automactic@mwoffliner2.mwoffliner.eqiad.wmflabs may mean clocks are out of sync.  Current drift is
45 seconds.  [orig: 2019-07-10 07:17:21.942842 recv: 2019-07-10 07:16:36.746610]

[2019-07-10 07:17:26,941: INFO/MainProcess] missed heartbeat from automactic@mwoffliner1.mwoffliner.eqiad.wmflabs
```

**Comment by rgaudin** [comment]
In this case, our _custom events_ (`container-started` and `container-finished`) were sent and retrieved properly.

The missing _event_ is `task-succeeded` which we process on the monitor but is not sent manually by us. Instead, it is automatically emitted at the end of the Task on the worker.

The presence of `Task offliner.mwoffliner[5d24550f6976bb2bc5e19ab7] succeeded in 44582..` in the log tells us our code didn't crash between our `container-finished` event and the end of the task as this message is an internal celery log once the task is executed.

Since this log is written right after [`task-succeeded`](https://celery.readthedocs.io/en/v4.3.0/userguide/monitoring.html#task-succeeded) is emitted, it's safe to assume it's been sent.

Possibilities:

* **A**. The handler on the monitor raised before/when saving data to mongo.
* **B**. The event was never received by the monitor.

**A**: we don't have the monitor log for this anymore (has been restarted since).
The code itself is [quite simple](https://github.com/openzim/zimfarm/blob/6ff42b5218df4c5cfe533a8a02c9a359486bd118/dispatcher/monitor/app/handlers/tasks.py#L144) and only moving part is the `files` parameter which we know is probably right given the _Upload files_ log trace above.

**B**: at this stage, this is my best guess. It could be of two reason:
* the message was lost while being transported. Pretty sure this would not happen with rabbit and would have failed/raised on the worker.
* **the monitor was not online at the exact moment the event was delivered**.

The monitor is _just_ a set of handlers (a `Receiver`) listening to the events emitted on the broker. Internal _TaskState_ change events are not queued like tasks so if our monitor is not listening when that event is broadcasted, then it won't be notified.

Rabbit does keep track of tasks states so what we could do is to **periodically check the individual statuses of unfinished tasks** and update the missing ones. I don't expect this issue to happen often but only time will tell.

---

Quick note on the hearbeat thing we see in the logs: the heartbeat mechanism is an app-level equivalent to TCP keepalive: packets are sent by clients (worker/monitor) to the rabbitmq server every `x` seconds and are returned back. That's an heartbeat. If your client misses 2 heartbeats, it is considered _offline_ and client will try to reconnect to the server. We are using the default value (set in the rabbitmq server) of 60s, meaning the round-trip should take 1mn (so heartbeat sent every 30s). To us, this is transparent and I don't think we want to change it. Just mentioning it in case you guys were wondering what those traces mean.

@kelson42, @automactic let me know if you're satisfied with the suggestion: a script that checks incomplete tasks' statuses in rabbit and update accordingly. We'd run it manually (or cron'd).

An alternative would be to not use Celery's task events and create an independent queue for our worker/backend communications. It would add code and complexity and seems odd as celery's role is to handle task management.

**Comment by kelson42** [comment]
@rgaudin @automactic I have still many questions open:
* Why we have no log on worker side about failing events (I guess there is some kind of acknowledge that events are received)?
* I don't see the relationship between the event and the status? To be able to recover from the status would mean that we have information redundancy!
* I'm not in favour of garbage collecting, infrastructure should be ready and otherwise a clear error should be generated.
* Why we don't know if the backend was online? We should be able to retrace when it was offline/online from the log.
* Why we can not have a more robust system of even sending (based on a retry mechanism)?

**Comment by rgaudin** [comment]
> @rgaudin @automactic I have still many questions open:
>     * Why we have no log on worker side about failing events (I guess there is some kind of acknowledge that events are received)?

because it didn't fail. The message was properly sent (because rabbit was online) but it was not recorded in the DB because the monitor was off. The message is sent to be broadcast but that's it.

>     * I don't see the relationship between the event and the status? To be able to recover from the status would mean that we have information redundancy!

We use a combination of custom and celery-generated events to update statuses. `task-succeeded` is a celery one and we update our status in DB when we receive it.

>     * I'm not in favour of garbage collecting, infrastructure should be ready and otherwise a clear error should be generated.

Agrees.

>     * Why we don't know if the backend was online? We should be able to retrace when it was offline/online from the log.

We have logs in docker but without any retention policy those are dropped every time we restart the container (valid both for the zimfarm and the workers).

>     * Why we can not have a more robust system of even sending (based on a retry mechanism)?

The sending succeeded. It's just that it was then immediately broadcast but no one was there to read it and update the DB.


As per our discussion, we can use a custom message using a custom exchange (with persistence) in rabbit for our internal messages (status updates mostly).

I suggest we focus rabbit-related discussion into #202 as it's the most pressing issue and its resolution might impact this one.

**Comment by rgaudin** [comment]
Another occurence: https://farm.openzim.org/tasks/5d723c171d1619754c6a4fae

**Comment by rgaudin** [comment]
other occurences:

* `wikipedia_en_all`: https://farm.openzim.org/tasks/5d723bee1d1619754c6a4fa7
* `vikidia_fr`: https://farm.openzim.org/tasks/5d723c171d1619754c6a4fae

**Comment by rgaudin** [comment]
Different occurences:

* https://farm.openzim.org/tasks/5d723c1d1d1619754c6a4fb5 `vikidia_it` started						container gone, no upload, no status
* https://farm.openzim.org/tasks/5d723c24efd26e8d5d6a4f4b `vikidia_en` started						container gone, no upload, no status [none on host]
* https://farm.openzim.org/tasks/5d723c2a1d1619754c6a4fbc `vikidia_ru` started						container gone, no upload, no status [none on host]
* https://farm.openzim.org/tasks/5d7240b5efd26e8d5d6a4f69 `wikipedia_ar_medicine` started			container gone, no upload, no status [none on host]

the last three ones were all on the same host (mwoffliner5).
