### ISSUE TITLE
Upload is slow (replace SFTP by SSH)

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#349]
I have tested manually upload with `curl` and the speed is around 130KB/s. By checking on the Web, we are not alone with that problem. SFTP is not really famous to be fast and the way how this is implemented by default in `curl` does not make things better.

We could speed up things by probably 100 just by using `scp` in stead of SFT. I have made a test with `scp -c aes128-ctr` which confirms this.

An other advantage is that we would not need anymore the custom SFTP server in Python becuase this would be replace by openSSH server... but this would have to be replaced by a small software in Python pulling time to time new SSH public keys to put them at the right place for SSH server.

**Comment by kelson42** [comment]
Even better, using a cmd to check authorized key. Read https://www.ssh.com/ssh/authorized_keys/openssh#location-of-the-authorized-keys-file

**Comment by kelson42** [comment]
A security should be make to never allow a std ssh connection.

**Comment by rgaudin** [comment]
done. the culprit was indeed cURL.

what's changed:

- warehouse to be retired as soon as tasks using it ends
- replaced by [zim-receiver](/zimfarm/tree/master/receiver) which also replaces kiwix's zim quarantine.
- new [uploader](/zimfarm/tree/master/uploader) supporting both SCP and SFTP.
 - both using openssh tools
 - both supporting compression (not interesting for ZIMs), bandwidth limitation and cipher selection

SCP and SFTP transfers are roughly equivalent in terms of speed. SCP is slightly faster but it's about 10s faster for a 4GB transfer so mostly negligible.

SFTP has a the advantage of supporting our `--move` option (transferring to a temp name and renaming afterwards) directly while with SCP, we transfer to `<name>.tmp` and once done we transfer a `<name>.complete` that would require server-side processing.
