### ISSUE TITLE
Improve worker robustness against network problems

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#356]
If a worker can not send its end status properly to the sceduler, then from the sceduler POV, this task will never end... We don't know how often this will happen... but for the moement, this is a situation whoch will need a manual operation to be solved.

**Comment by kelson42** [comment]
IMO, if the scheduler can not aknowledge a msg from a worker, then the worker should try again (and be blocked) as long as necessary to get acknowlegement.

**Comment by rgaudin** [comment]
I disagree.
Forever loop on network requests is generally a bad practice, especially on a failed request.
It could occur (at least) when:
* network issue on worker
* network issue on scheduler
* scheduler offliner (moving, restarting, etc)
* bug in scheduler endpoint
* API change in scheduler

we already have an example of a forever loop call to the API due to an API change (SSH auth endpoint).
I see no advantage in looping until the network comes back as if this happens during the 99.9% of the time where the scraper is running, the job will fail (scrapers don't support that).

from a maintenance perspective, if I have long task in the dashboard that I suspect, I'd find it easier to check on the worker if the task is running (ps) than have to check its actual log to check if it's in that loop.

for those reasons I think that retrying several times within a 20mn? period is a good compromise. If it was a network issue, it's would probably be fixed. If it was and is not fixed, then the task will most likely fail and we won't receive a notification. we'd have a dangling task on our dashboard that we can manually mark as failed.

**note**: given the number of task which apparently succeeded but did not receive the final `succeeded` status update, I think we have a different bug there so fixing it might make this all a lot rarer.
