### ISSUE TITLE
Cross-Origin Request Blocked: preflight request failed

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#387]
This happens time to time (Firefox, Ubuntu 18.04) whatever the URL I think. Simple reload of the page is enough to workaround it.

![image](https://user-images.githubusercontent.com/1029718/72666365-b09aa000-3a11-11ea-97d5-fe0cee8b2c1f.png)

**Comment by kelson42** [comment]
@rgaudin I don’t have seen this error since many weeks. Might that be that you have foxed it?

**Comment by rgaudin** [comment]
I don't **fox** issues :) but no I didn't fix anything related to this. actually the UI code hasn't been touched in a long time. I'll mark it as needing a reprocase and we'll look at it when someone encounters it.

**Comment by kelson42** [comment]
Seems to have reappeared for me.

**Comment by rgaudin** [comment]
Did you notice if it was right before your token being refreshed?

**Comment by kelson42** [comment]
@rgaudin Seems unrelated.

**Comment by rgaudin** [comment]
Ok, seems like some requests randomly don't set CORS header: `‘Access-Control-Allow-Origin’ missing`.

Will check if there's an upstream bug or if it's an incorrect usage of `flask-cors`.

**Comment by kelson42** [comment]
The days I use the Zimfarm intensively and I get this error many times a day.

**Comment by rgaudin** [comment]
It's a feature to prevent you from using the zimfarm too much 😀

My last experiments on this leans toward the reverse proxy (at sloppy for us) being responsible for this. It's difficult to be sure as I can't reproduce it.

Problem is, some OPTIONS request answers randomly don't include CORS header. I'm pretty sure our code always sets it but wanted to try with apache-bench or similar (`ab` doesn't support `OPTIONS`).

I'm removing the reprocase flag as this is happening frequently to you.

**Comment by rgaudin** [comment]
I've encountered this again today but still don't have a real clue. According to [doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed), it's a network issue and that's what the firefox devtools show (no connection after DNS resolution). That makes sense with the earlier server-side code investigations… but that doesn't help in finding a fix.

I've tried to stress the server to check if it was reproducible (using [hey](https://github.com/rakyll/hey)) but could not.

**Comment by kelson42** [comment]
@rgaudin Have you already been in touch with Sloppy about this specific problem?

**Comment by rgaudin** [comment]
No, as I said, I can't reproduce it even when generating hundreds of thousands of requests.

Also, we're only seeing those in ajax requests that are constructed by the [axios](https://github.com/axios/axios) library through our [Vue](vuejs.org/) code. So that's additional variables in the equation. I couldn't find any trace of similar issue on those projects (all CORS issues are related to beginners not using CORS properly).

But… manually requests are very few compared to the number of automated requests we do via ajax, so that could explain why we don't see occasional http errors.

What we could do to move forward is to check whenever this happens (network issue) and retry **once**. That won't help us understand the cause (if there's any to find) but it may reduce the inconvenience of that message.

**Comment by kelson42** [comment]
> What we could do to move forward is to check whenever this happens (network issue) and retry **once**. That won't help us understand the cause (if there's any to find) but it may reduce the inconvenience of that message.

I'm in favor of that. Bumping axios/vue dependences might help as well.

**Comment by kelson42** [comment]
It seems it does not happen so often anymore and we don’t know anyway how to really improve the situation. We will have to live with this.
