### ISSUE TITLE
Support (and hide) new MWoffliner option "--optimisationCacheUrl="

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#404]
We should be able to set this new optional parameter (is a string) and we should secure that the value of this option is never displayed to anonymous users (both in the UI or logs).

I would like also that see the youtube API token hidden in the same manner.

**Comment by rgaudin** [comment]
First of all, I think that regardless of the way we protect those credentials (because that's what it contains), we **should** block network access to this server and [white-list our workers](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-3).

Now before we start implementing this, I'd like to highlight how much of a change this feature implies:

* `/schedules/xxx`, `/requested-tasks/xxx`, `/tasks/xxx` would all need to be transformed depending on the caller.
* returning different content on the same URI, using the same HTTP status code is bad behavior in general.
* would API users be informed that they are getting a different version of the data? how?
* what would be the returned data for them? Should we remove the *credential-flag* or should we return it with a placeholder content?
* we could work around those by duplicating those three endpoints but it would be a bit ugly, break the REST architecture and require a lot of duplication in the API documentation.
* At the moment, we (or anybody) can dump our whole recipes collection as a backup. we'd need to change that as well.
* we'd have to introduce a new permission set as we'd want the `worker` role to be able to read them.
* UI needs to be changed to:
  * `/recipes/xxx/config` with conditional display of config and docker command
  * `pipeline/xxx/debug` with conditional display of config and command
  * what happens for edition? would recipe-edition imply credentials access? If not, what happens when a regular editor wants to edit an mwoffliner recipe? If there was a credential flag, can he see it ? Can he update it ? If there was not, can he add one?
  * what happens for cloning? Should the cloned recipe drop the field or copy it with a placeholder?
* broadcaster should be modified to exclude those info on `requested-task` events
* scraper flags are not displayed in the workers. It's barely handled when starting the scraper and then the scraper command is sent once to the API to mark it as started.
* scraper logs are uploaded as-is straight from filesystem to the server so that we're able to efficiently upload progress as they come. Those are downloadable publicly. manipulating the scraper logs would mean:
 * rewriting log upload part
 * adding hard-to-maintain, scraper-specific code in the worker
 * less efficient.
* but we could of course just require that scrapers with sensitive params provide an additional param to hide it (`--hide-sensitive-info`?) and that would be the scraper's responsibility to not leak it in the logs.

So, all in all, it's a major change.
