### ISSUE TITLE
workers readme: Uploading your public key

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#406]
[//]: # (Pick appropriate classifiers)
- Location: Worker

## Problem

I prefer other kind of scripts:

It would be nice, if I don't have to copy'n'paste things. That could be a reason for a mistake.

My-Key-Name="replace-this" # Set your key name here
My-Token="insert-token" # Your token can be found in the webinterface 
My-Public-Key=`cat id_rsa.pub | cut -d " " -f 2` # your public key gets extracted from the file id_rsa.pub.

## Reproducing steps

[//]: # (Information on how to reproduce it.)

**Comment by rgaudin** [comment]
Thanks @JensKorte. As you may know, the new-worker procedure hasn't been used much so it's a good opportunity to improve it. That said, the **bug** label is reserved for stuff that are not working. Here, I think we're looking at an **improvement* of the doc. So I'll change the label.

Could you give a little more detail on what your issue here? I re-read the README and am not sure about what part you're talking about? Is it about the upload key step? 

If so, I understand that you'd prefer to set-up a couple variables to set the customized info and then have a copy-paste friendly command that uses those to upload the key. Is that right?

That makes sense ; please confirm.

**Comment by JensKorte** [comment]
Yes, you are right. If a bug happens, it is possible to upload the whole file and see how it was configured since some variables are set by editing the file.

**Comment by JensKorte** [comment]
Instead of having a copy-paste friendly command it could be an extra shell script, that can be downloaded with wget or curl and that command would be in the readme

**Comment by kelson42** [comment]
To me it looks like this ticket is a duplicate of #363

**Comment by kelson42** [comment]
I will close this ticket because we should have a UI and then there is nothing much to do here.
