### ISSUE TITLE
should we crash on image pull?

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#411]
Because we mostly fire docker containers, we have a strong dependency on the docker hub ; especially given the fact that we always pull our images before running them (regardless of their presence on disk or tag).

It's been a bit problematic in the past as sometimes the hub is unresponsive and we would crash trying to pull an image.

We worked around this by making docker requests safer, retrying upon errors.

Today, the hub was not responding properly for a few minutes (`lookup auth.docker.io on 208.80.154.24:53: server misbehaving` for instance), exceeding our retries policy, thus crashing several runs.

Sure it's an external event but crashes happened on pulling the `openzim/uploader` image which was definitely present ; because we're instantiating this image very frequently (for log updates)

Questions:

* should we not crash on pull issues ?
  * For which image? We have manager, task-worker, uploader, dnscache and all the scrapers
  * Only if it's present on disk (of course)
  * Only if it's been pulled in the last 24h?

@kelson42 we should discuss those details so that we only crash when it's _required_ (subjectively)

**Comment by kelson42** [comment]
I think we should always pull if we have not specific tag or using `latest`. Otherwise I hardly see why it could make sense (except if we have the habit to override releases, but we don't have it). So I would change the rule that way to be more efficient. I think this attitude of always pulling is inherited for the Zimfarm first times, where we were using `latest` all the time.

That aside, if we need to pull and the image repository is unresponsive, then I think we should try harder/longer, in fact I don't see why we should not try indefinitely.

**Comment by rgaudin** [comment]
Closing this as the updated retry mechanism should prevent the root cause of this from hapening.
