### ISSUE TITLE
Logs should probably be uploaded to S3 instead of download.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#472]
From the principle S3 is a better place to upload the scraper logs. It would keep place for more ZIM files, etc. on download.kiwix.org. It would be also leaner to handle the whole lifecycle like this.

Related to #373

**Comment by rgaudin** [comment]
agrees. what should be the duration before deletion?

**Comment by kelson42** [comment]
Around 2 months?

**Comment by kelson42** [comment]
The problem here is probably that we can not upload on the fly. This is why I believe this ticket is related to #462 and #331. We should probably provide a better way to know what is happening _live_ on the zimfarm (progress, log trail). But upload the whole log at the end of the the S3.

**Comment by kelson42** [comment]
Or we should use a proper/dedicated log analysis tool.

**Comment by rgaudin** [comment]
What would be the added value? All those logs are only usable for a very short period of time, almost exclusively when the task is running and on failures and I don't see how it could be analyzed in any useful manner.

If it's only for having easy access to the trail, I think it's not worth the cost but maybe it allows us to stream logs and don't have to store it…

I think we should group all logs-related tickets and list the problems and needs that we have because we need to address them together.

**Comment by kelson42** [comment]
Yes, we should create a tag "Logging" so we can have a good overview at the time we will work on this.
