### ISSUE TITLE
Logs are time-to-time so big that the scraper get short on storage and crashes

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#478]
We should see if we can do something smart to improve the situation.

**Comment by rgaudin** [comment]
It is indeed possible to configure docker to rotate the logs and keep at most 100MB for example but we would have to write a different log upload mechanism.
The current one is light and solid because we're uploading a file and thus delegating most of the work to scp/sftp.

We could check the logs constantly and upload what changed but it would be a good addition of code for that feature, and we'd either loose the benefits of scp (compression, no backend) or have to duplicate those logs-to-upload to a file and use the existing tools.

My concern is that we're in a long-lasting temporary situation. All mwoffliners recipes (972) have verbose enabled. My understanding is that this is a debug feature enabled to track a bug. So I'm a bit reluctant to introduce complexity and maintenance cost for something that's temporary.

An easy alternative would be to configure workers properly to account for very large logs and adjust disk space config. This has not been correctly done for `protocol` because its disk is relatively small and we agreed we'd resize it. That requires a couple  of hours of it offline though. We can do that this week if you'd like.

Also, beside `mwoffliner5`, other workers have not been reconfigured to have logs on `/srv`. Maybe it didn't fail so far because those are not taking super large task and thus the logs are not as big, but it would be good to schedule this and forget about it before we just forget about it without doing it :)

**Comment by kelson42** [comment]
@rgaudin Agree. We should configure all the boxes to deal with larger logs then as a first measure. We plan to make a new MWoffliner release on Thursday which will generate a lot more logs. We should be ready to handle them at the time we will update the Zimfarm recipes.

**Comment by rgaudin** [comment]
How much space should we expect the logs to take at most ?

**Comment by kelson42** [comment]
I really don’t know, put the mx you can

**Comment by rgaudin** [comment]
That's not how it works. We configured the disk space for the worker according to the space available. So we'd have to reduce that to accommodate logs.
I have seen 20GB large log files so I know this must be at least 20GB but you're saying a lot more logs now… 

We should probably also considare the fact that smaller workers do smaller tasks and thus have smaller logs…

here's the config at the moment

```
mwoffliner1.mwoffliner.eqiad.wmflabs
ZIMFARM_DISK="100G"
mwoffliner2.mwoffliner.eqiad.wmflabs
ZIMFARM_DISK="100G"
mwoffliner3.mwoffliner.eqiad.wmflabs
ZIMFARM_DISK="40G"
mwoffliner4.mwoffliner.eqiad.wmflabs
ZIMFARM_DISK="220G"
```

**Comment by rgaudin** [comment]
OK, all wmf workers have been reconfigured. Here's a table of HDD and zimfarm storage I've set. The docker and logs column are just conceptual.

| worker | HDD | docker | logs | zimfarm |
| --- | --- | --- | --- | --- |
| mwoffliner5 | 190G | 8G | 37G | 145G |
| mwoffliner4 | 240G | 8G | 37G | 195G |
| mwoffliner3 | 50G | 8G | 7G | 35G |
| mwoffliner2 | 120G | 8G | 17G | 95G |
| mwoffliner1 | 120G | 8G | 17G | 95G |

FYI, docker folder on nfs share did not work as docker wants to chown files on start which is not possible on nfs.
