### ISSUE TITLE
Web task view should display a few additional info

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#507]
I miss:
* <s>The name of the user who has scheduled the task</s> It is there on the right in the requested event line
* The version of the scraper (Docker image tag)

**Comment by rgaudin** [comment]
The user who scheduled (requested) the task is already there.

**Comment by satyamtg** [comment]
This can be fixed in two ways -
1. Have the frontend changed to request specific tasks data for all tasks (to get config.image.tag)
2. Change the backend to send config.image on the /task/ route and add a single line in the frontend

I prefer going the second way as the first one would mean many more API requests. What do you suggest @kelson42 @rgaudin  ?

**Comment by rgaudin** [comment]
@satyamtg I think you misunderstood the ticket. @kelson42 is referring to https://farm.openzim.org/pipeline/5ef60ca39ec57a810572bf6f for instance (or the `/debug` sub page).

There we already retrieved the `/tasks/xxx` from the API so we have all the info at hand.
This ticket is thus very simple. ie. adding a row and displaying the value.

**Comment by satyamtg** [comment]
Okay. I get it. I thought we wanted to do that in the tasks list in the pipeline view. My bad. Anyways this is simple then.
