### ISSUE TITLE
Worker unable to find/upload log

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#581]
https://farm.openzim.org/pipeline/825e4e3a931328f2e9fc5df5/debug

**Comment by rgaudin** [comment]
this has nothing to do with S3. Logs are uploaded fine and you can download them.
It's the task-worker log that could not be uploaded.
this is done by the manager. I've seen this in the transition to new ids but not since workers were restarted. Will check.

**Comment by rgaudin** [comment]
OK, this was due, as expected, to the task ID change. We are now creating containers with names such as `zimtask_xxxxx` while we were previously using `xxxxx_zimtask` (so it's easier to jump from one another).

Those failing ones are all trying to reach the new format but containers were created with old format.
For tasks started before the fix, this bug is to be expected. For those started recently, what happened is unclear as it's the same line of code being called for both actions (creating zimtask container and checking its log) and both are inside the manager, so in the same docker image…

restarted the workers. Seems to be working now. Fixed for all tasks `reserved` after now.
