### ISSUE TITLE
New ZIM of lesfondamentaux is really too small

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#623]
It is super urgent we understand if we don't have a regression here.

**Comment by rgaudin** [comment]
@kelson42 https://lesfondamentaux.reseau-canope.fr/international is now behind a paywall. Homepage seems to imply it used to be that way (before covid?).

What we got in recent runs is that homepage. Loaded videos are working but not the three other ones available on click (I guess not scraped due to the JS dynamic link). 

Anyway, it's not available anymore. We should remove the recipe.
