### ISSUE TITLE
Stat filename should not be a parameter

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#633]
It is currentky a parameter which can/should be set manually. This seems to me not user friendly. IMO it would be simplier to just use it if available in the scraper and hard ode the value in the zimfarm.

**Comment by rgaudin** [comment]
Actually, this does not need to be set at all. It is set automatically by the code if the scrapper supports it. It just happens to be visible on the UI because it's part of the recipe and is validated as any other field.

FYI;
You were mistaken because a test sotoki recipe couldn't be updated via UI because of an _incorrect_ `StatsFilename` value.
It just happened that this parameter was renamed in the scraper but the recipe had the previous name in it.
Whenever a scraper's CLI param changes, the zimfarm has to be updated obviously. First in the _offliner_ code that specifies what the expected parameters are and in the DB, to update recipes. This is regardless of the parameter and is up to the developer updating the offliner code to do. Hasn't been done yet for that particular recipe as it was a _dev_ one, as its name suggest.

Closing this.
