### ISSUE TITLE
Strange failing behaviour

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#669]
At https://farm.openzim.org/pipeline/filter-failed we see a bunch of wikimedia related scrapes which fails one or two time and are automatically rescheduled. This shoukd not happen. It seems to happen only with worker michaelblob.

**Comment by rgaudin** [comment]
Those are canceled after being requested+assigned to the worker but the scraper never starts. It's a feature of the zimfarm.

This usually happens when the task-worker cannot start for some reason. We'd need the logs of the failing-to-start task containers and the manager to find the actual cause.

I'd start by restarting the manager first though. Ask the worker owner to contact us on Slack if that doesn't fixes it.
