### ISSUE TITLE
Schedule column always empty under certain conditions

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#720]
Recipe view looks good with pagination at 10
![A123B034-FB26-4D87-B05A-332077BA2A8A](https://user-images.githubusercontent.com/1029718/194646847-3e61e5b6-10c1-421c-ba37-43d5a971093a.png)

But with pagination at 50, the schedule column is empty
![51A8F65F-7DF9-4496-9405-40CD13856C23](https://user-images.githubusercontent.com/1029718/194647032-7f0278af-d1c8-425f-9359-e416be2c08d5.png)

**Comment by rgaudin** [comment]
Good catch! It's due to incorrect handling of the limit (your filter has less entries than the limit)

**Comment by benoit74** [comment]
Isn't this already fixed? See https://farm.openzim.org/recipes?category=ifixit for instance.

**Comment by rgaudin** [comment]
No it's not. @benoit74 we're looking at the column with a clock that contains a tick if the schedule is _requested_ (has a requested-task).

ATM, there are only wikihow recipes in the pipe
<img width="1209" alt="Screenshot 2023-09-29 at 08 06 51" src="https://github.com/openzim/zimfarm/assets/57929/54df8d18-ea62-4b60-b882-6117f070deee">

In the recipes list, with a pagination of 20, I do get the ticks
<img width="1141" alt="Screenshot 2023-09-29 at 08 07 04" src="https://github.com/openzim/zimfarm/assets/57929/b39724bf-034b-43a4-9dc5-9936639c5779">

But if I change to 50, the ticks are gone
<img width="1131" alt="Screenshot_2023-09-29_at_08_07_12" src="https://github.com/openzim/zimfarm/assets/57929/27d83102-a5ff-4744-b12a-5742cd73cb75">

**Comment by benoit74** [comment]
This is linked to an underlying HTTP error at UWSGI level. By default UWSGI limit the request size to 4096 bytes.

When there is a lot of schedules, the UI does a pretty big query to retrieve all requested tasks due to the addition of all schedule names:
`https://api.farm.openzim.org/v1/requested-tasks/?limit=50&schedule_name=wikihow_ar_maxi&schedule_name=wikihow_cs_maxi&schedule_name=wikihow_de_maxi&schedule_name=wikihow_en_endless&schedule_name=wikihow_en_endless_arts-and-entertainment&schedule_name=wikihow_en_endless_cars-and-other-vehicles&schedule_name=wikihow_en_endless_computers-and-electronics&schedule_name=wikihow_en_endless_education-and-communications&schedule_name=wikihow_en_endless_food-and-entertaining&schedule_name=wikihow_en_endless_hobbies-and-crafts&schedule_name=wikihow_en_endless_holidays-and-traditions&schedule_name=wikihow_en_endless_home-and-garden&schedule_name=wikihow_en_endless_personal-care-and-style&schedule_name=wikihow_en_endless_sports-and-fitness&schedule_name=wikihow_en_endless_work-world&schedule_name=wikihow_en_endless_youth&schedule_name=wikihow_en_maxi&schedule_name=wikihow_es_maxi&schedule_name=wikihow_fa_maxi&schedule_name=wikihow_fr_maxi&schedule_name=wikihow_hi_maxi&schedule_name=wikihow_id_maxi&schedule_name=wikihow_it_maxi&schedule_name=wikihow_ja_maxi&schedule_name=wikihow_ko_maxi&schedule_name=wikihow_nl_maxi&schedule_name=wikihow_pt_maxi&schedule_name=wikihow_ru_maxi&schedule_name=wikihow_th_maxi&schedule_name=wikihow_tr_maxi&schedule_name=wikihow_vi_maxi&schedule_name=wikihow_zh_maxi`

I see three options:
1. adapt the `/schedules` endpoint to also return the info about the presence of a requested_task: a boolean property `task_requested`
2. in the UI, get all requested-tasks to populate this view and filter in the UI ; use a default pagination of 100 items and a loop to fetch all requested-tasks ; do not keep the list of requested tasks in memory, only the info which interests us: is there a requested task for the given schedule ; the list of requested-tasks is expected to always be small + filtering them on the fly should be ok
3. adapt UWSGI configuration to increase maximum request size

I prefer option 1 because it is the more straightforward solution ; performance impact is probably minimal because when have an index at hand + the number of requested tasks is expected to be small ; the endpoint is then maybe a bit less "RESTfull" but who cares?

I don't like option 3 because this is the kind of setting which has been chosen for good reasons, and changing it just for a "not-adapted" HTTP endpoint is not a good practice IMHO.

**Comment by benoit74** [comment]
If we choose option 1, we should probably adapt `GET /schedules` and `GET /schedules/{schedule_name}` for consistency

**Comment by rgaudin** [comment]
I agree changing it in uwsgi would not be wise. 4KiB is a lot and browsers may strip it anyway.

I am also in favor of 1. `is_requested: bool` is a schedule-related info and data model should not dictate the API. It's semantically different from `requested_task_id` for instance.
