### ISSUE TITLE
Clarify that the `Description` field is best limited to 100 characters.

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#739]
Otherwise there is an unsightly cut on the hotspot dashboard
![farm100](https://user-images.githubusercontent.com/21675885/215529207-e2394a96-fa9c-4c17-bb78-2aeb20403326.png)

What I am not sure I understand is why the cut isn't applied on regular Kiwix-server (or conversely why the Kiwix-server character limit isn't on the hotspot)?

**Comment by rgaudin** [comment]
This is reader-specific. There is a discussion somewhere that I can't find at the moment about those description length because ATM we have no recommendation or limit and each reader does as it pleases.
This is an arbitrary limit on the hotspot homepage generator that we don't have in the *new* home.

**Comment by kelson42** [comment]
The spec, says 80. https://wiki.openzim.org/wiki/Metadata

**Comment by rgaudin** [comment]
Yes, since that discussion ; this is very new recommendation that hasn't been passed down to scrapers

**Comment by rgaudin** [comment]
@kelson42 Can you find that ticket I mentioned? It would be helpful ; mostly because most readers don't use `LongDescription`

**Comment by kelson42** [comment]
I don't remember and can not find it anymore :( but we implememt it right now in MWoffliner https://github.com/openzim/mwoffliner/issues/1663.
