### ISSUE TITLE
Querying container status times out

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#749]
At least never for https://farm.openzim.org/recipes/wikipedia_en_all.

I don't see the "Download" button.

... and I have no clue why, but I need them.

**Comment by rgaudin** [comment]
For the record, the worker sends the last 5K lines of logs from stdout and stderr every minute. That's what's directly visible.

The full scraper log is uploaded to S3 as a file **after the container has exited**. This is regardless of the scraper exit code but this only happens on exited scraper, not on killed tasks (cancelation mostly).

So it's normal not to have it for canceled tasks. Worker tries to remove everything and release resources ASAP.

- [2023/01/09 - mwoffliner4](https://farm.openzim.org/pipeline/350003b8b8f543a5991c4b36): `container.reload()` timed out
- [2022/11/02 - mwoffliner4](https://farm.openzim.org/pipeline/c6628bb0136e06fb89322636): `container.reload()` timed out
- [2022/08/01 - athena18](https://farm.openzim.org/pipeline/71e8970110876a065fd57e26): scraper exited with `1`, log is present.
- [2022/07/03 - athena18](https://farm.openzim.org/pipeline/c868a1889c1ebb3ef3b7eb26): scraper exited with `1`, log is present

Haven't looked past this. So for this recipe, it's two runs that were halted because the worker code could not query the container's status (similar to `docker inspect`). Both were on the same worker host but it's only two runs, so hard to conclude anything.

I believe we've seen this kind of behavior in the past and we decided that if we can't contact the docker daemon within 3mn (180s), then things are probably not going well and we should tear it down (let it crash).

I see that mwoffliner4 is using an old docker version (`20.10.16` May 2022) while `23.0.1` is available. I suggest we upgrade docker and restart the recipe to see how it goes.

Actually we should update docker on all the workers we have access to. If that's OK with you, we can switch them to selfish and wait for their current tasks to complete to upgrade.

**Comment by kelson42** [comment]
In favour of upgrading Do ker indeed.

**Comment by rgaudin** [comment]
mwoffliner4 has been upgraded ; other mwoffliner workers are being upgraded now. Please restart that recipe and reopen the ticket if the log is still not uploaded.
