### ISSUE TITLE
Filtering File Name issue

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimfarm#775]
As per issue https://github.com/openzim/zim-requests/issues/621 . I see that we could filter the files with long descriptions in order to fix them.
Can we filter failed recipes in Zimfarm with naming issues so we could fix them all?

**Comment by rgaudin** [comment]
No, we can't. Reason for failure is not an information we get. At best, it's a somewhat clear message in the logs.
This is not something we plan to work in the foreseeable future.

That said:

- we want to prevent creating recipes with incorrect description. Quite easy.
- this won't prevent some scrapers to create ZIM with _incorrect_ metadata. I am thinking of YT recipes with dynamic metadata for instance.

This should eventually be handled in the CMS ; I believe zimcheck now support those since `3.2.0` (now used by zimfarm). Eventually, we may may improve the zimcheck dashboard on the CMS to list corresponding Books.
