### ISSUE TITLE
Illustration seems not always retrieved properly

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#792]
Here is my recipe:
https://farm.openzim.org/recipes/att_connected_learning_en

Here how it looks online in kiwix-server:
https://dev.library.kiwix.org/#lang=eng&q=connected+learning

![image](https://github.com/openzim/zimfarm/assets/1029718/2028905a-f11e-4724-9d48-501f68191578)

So the illustration is not visible and when I go straight to the API it seems the binary data is broken https://dev.library.kiwix.org/catalog/v2/illustration/73364dbf-5f45-2127-91ef-8382ab200105/?size=48

**Comment by rgaudin** [comment]
Several issues at play:

- First, it wasn't retrieved properly because Wikimedia server prevented it (they have a User Agent Policy)
- Second, we are not yet using scraperlib 3.1 with warc2zim (we'll do very soon) so if we don't have an icon we don't set it.
- There are known cases where we won't have an icon and the plan is to set either a blank PNG or a custom _Illustration missing_ PNG in those cases.
- Third, kiwix-serve returns a 200 response with  `content-length: 0. This seems incorrect. It could be a 404 but the spec requires an illustration, so it's arguable.

```
[WARNING] Unable to retrieve favicon. ZIM won't have an illustration: 403 Client Error: Forbidden. Please comply with the User-Agent policy: https://meta.wikimedia.org/wiki/User-Agent_policy for url: https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/AT%26T_Globe_2016.svg/600px-AT%26T_Globe_2016.svg.png
```

**Comment by kelson42** [comment]
Looks like we wil need 4 tickets ;)

**Comment by rgaudin** [comment]
Indeed
