### ISSUE TITLE
Add freecodecamp support

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#804]
New offliner for https://github.com/openzim/freecodecamp

**Comment by benoit74** [comment]
Small points that needs to be confirmed :
- we support only the `all` command of `fcc2zim` (individual commands `fetch`, `prebuild`, `zim`) makes no sense in Zimfarm
- we need a new platform in addition to the new offliner, in order to limit the number of tasks for fcc2zim per worker
- we limit to 1 fcc2zim task per worker for now
- output flag is not standard: "outpath" instead of "output"
- there is no support for the JSON stat file in fcc2zim (for now)

**Comment by benoit74** [comment]
This task is not possible to complete, work on https://github.com/openzim/freecodecamp/issues/11 needs to be finished (at least first point on CLI parameters) for this task to make sense (otherwise no one but few devs will be able to create recipes for this scraper)

**Comment by benoit74** [comment]
I pushed some WIP code on https://github.com/openzim/zimfarm/tree/add_fcc (probably almost ready except Flags / CLI parameters)
