### ISSUE TITLE
Missing carriage returns in log output

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#924]
Not sure this is for zimfarm but in recent youzim runs (like [this one](https://farm.youzim.it/pipeline/4ad054a0-4015-42c1-be36-931aa2916ba3/debug)), I notice missing `\n` in the zimfarm UI log 

<img width="1162" alt="Screenshot 2024-02-26 at 09 56 59" src="https://github.com/openzim/zimfarm/assets/57929/9cd819c8-c8e4-468e-b3a8-4749a2f6bcc3">

**Comment by benoit74** [comment]
This is a weird issue in a corner-case because:
- data in the DB is really missing the carriage returns
- the issue seems to be here since quite some time (at least tasks from 2 months ago are impacted: https://farm.youzim.it/pipeline/033bb35a-5992-4e77-ac89-4e35228f617e/debug)
- the issue seems to not be systematic (here we have carriage returns: https://farm.youzim.it/pipeline/1734ae38-10c9-480d-b1ed-2d1b7e3396dd/debug)
- the issue seems limited to youzim.it instance
- I do not reproduce the issue locally
