### ISSUE TITLE
Adapt Zimfarm to MWoffliner 1.14

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#988]
We are just a few step away from the release of MWoffliner 1.14.0. This release went through significant changes, both internally and externally. Therefore the command line arguments have slightly changes and ZIMfarm will have to adapt.

**Comment by kelson42** [comment]
This will need a few changes and a bit of beta-testing will be needed. I will list the changes later but alreqd want to propose the following workflow:
* Disable all recipes
* Apply changes in ZIMfarm
* Reactivate a few recipes to test
* When everything OK, reactivate all recipes (which were activated before)

@benoit74 Does that sound good?

**Comment by benoit74** [comment]
Great, that's a good new !

Recommendation is now clearly to do the tests in `/.hidden/dev`, even if we expect the consequence to be minor, and only then to move to prod. When a bad ZIM is published in production, it is a bit of a mess to rollback due to consequence on library **AND** imager service, so I recommend to take this into account even if it adds complexity to the workflow.

**Comment by benoit74** [comment]
This is operational stuff, so better tracked in https://github.com/kiwix/operations/issues/214
